hooks: added hook for doc sync.
dart-lightning/lndart.cln pull request #79
Opened 2022-07-22 09:49 UTC by swaptr

This hook will update `docs/index.mdx` if there were changes in `README.md.
Note: Merge after #78 for a cleaner commit history :)

2022-07-22 09:52 UTC, vincenzopalazzo reviewed
Good thanks!

There is only a change that you need to make in the other PR

2022-07-22 09:57 UTC, swaptr commented
Wait I need to make the `hook` accessible. How can I do that?

2022-07-25 12:29 UTC, vincenzopalazzo commented
>Wait I need to make the hook accessible. How can I do that?

What type of hooks are you talking about?

2022-07-25 12:34 UTC, swaptr commented
I am talking about git hooks.

2022-07-25 12:46 UTC, vincenzopalazzo commented
Ignore it, we have more important stuff to do

2022-07-25 15:30 UTC, vincenzopalazzo requested changes

2022-07-25 15:30 UTC, vincenzopalazzo commented on docs/index.mdx
> +    <strong> :dart: Dart framework for Core Lightning :dart: </strong>
```suggestion
    <strong>  Dart framework for Core Lightning  </strong>
```

2022-07-25 15:30 UTC, vincenzopalazzo commented on docs/index.mdx
> +   <img alt="GitHub Workflow Status" src="https://img.shields.io/github/workflow/status/dart-lightning/clightning.dart/Sanity%20Check?style=flat-square">
```suggestion
   <img alt="GitHub Workflow Status" src="https://img.shields.io/github/workflow/status/dart-lightning/clightning.dart/Sanity%20Check?style=flat-square"/>
```

This should be fix the docs page

2022-07-25 15:38 UTC, vincenzopalazzo commented on docs/index.mdx
> +   <img alt="GitHub Workflow Status" src="https://img.shields.io/github/workflow/status/dart-lightning/clightning.dart/Sanity%20Check?style=flat-square">
This is not magic, I use the https://mdxjs.com/playground/ and it show the error and the line

2022-07-25 16:08 UTC, vincenzopalazzo approved these changes

2022-07-25 16:25 UTC, vincenzopalazzo approved these changes

2022-07-25 16:25 UTC, merged